# This is the main workflow file. It is run every time a PR is merged
# Required env:
# NPM_TOKEN
# GITHUB_TOKEN
name: Main workflow
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      # Setup the node environment
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      # Install dependencies
      - run: npm ci --prefer-offline
      # Release npm package
      - run: npm run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
          NPM_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
